-- ============================================================
-- P0: Spring Boot 自动初始化 — 认证与审计表
-- 通过 spring.sql.init.mode=always 自动执行
-- ============================================================

CREATE TABLE IF NOT EXISTS t_user (
    id          BIGSERIAL       PRIMARY KEY,
    username    VARCHAR(64)     NOT NULL UNIQUE,
    password    VARCHAR(256)    NOT NULL,
    email       VARCHAR(128),
    role        VARCHAR(32)     NOT NULL DEFAULT 'VIEWER',
    enabled     BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_username ON t_user(username);

CREATE TABLE IF NOT EXISTS t_refresh_token (
    id          BIGSERIAL       PRIMARY KEY,
    user_id     BIGINT          NOT NULL REFERENCES t_user(id),
    token       VARCHAR(512)    NOT NULL UNIQUE,
    expires_at  TIMESTAMP       NOT NULL,
    revoked     BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON t_refresh_token(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires ON t_refresh_token(expires_at);

CREATE TABLE IF NOT EXISTS t_audit_log (
    id            BIGSERIAL       PRIMARY KEY,
    user_id       BIGINT,
    username      VARCHAR(64)     NOT NULL,
    action        VARCHAR(64)     NOT NULL,
    resource      VARCHAR(256),
    detail        TEXT,
    ip_address    VARCHAR(64),
    success       BOOLEAN         NOT NULL DEFAULT TRUE,
    error_message TEXT,
    created_at    TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_user_time ON t_audit_log(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action ON t_audit_log(action);

-- ============================================================
-- P1(1.3): 审计事件幂等键 —— Kafka 至少一次投递 + 消费端 ON CONFLICT 去重
-- ============================================================
ALTER TABLE t_audit_log ADD COLUMN IF NOT EXISTS event_id VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_event_id ON t_audit_log(event_id);

-- ============================================================
-- P1(1.3): 会话统计聚合表（DashboardStatsConsumer 增量维护；
--           aether.dashboard.stats-source=kafka 时 DashboardService 读此表）
-- ============================================================
CREATE TABLE IF NOT EXISTS dashboard_stats (
    agent_id          VARCHAR(128)   PRIMARY KEY,
    sessions_total    BIGINT         NOT NULL DEFAULT 0,
    turns_total       BIGINT         NOT NULL DEFAULT 0,
    tool_calls_total  BIGINT         NOT NULL DEFAULT 0,
    tool_errors_total BIGINT         NOT NULL DEFAULT 0,
    tokens_total      BIGINT         NOT NULL DEFAULT 0,
    cost_usd          DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- ============================================================
-- P1(1.3): Agent 事件消费幂等表（event_id 去重；审计链路由 uk_audit_event_id 承担）
-- ============================================================
CREATE TABLE IF NOT EXISTS aether_processed_event (
    event_id     VARCHAR(64) PRIMARY KEY,
    event_type   VARCHAR(64),
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- D1: 异步委派表（hermes async_delegations 对齐）
-- ============================================================
CREATE TABLE IF NOT EXISTS t_async_delegation (
    id                   VARCHAR(64)  PRIMARY KEY,
    parent_session_id    VARCHAR(128) NOT NULL,
    parent_agent_id      VARCHAR(128),
    task_payload         TEXT         NOT NULL,
    tool_names           TEXT,
    state                VARCHAR(32)  NOT NULL,
    attempt_count        INTEGER      NOT NULL DEFAULT 1,
    result_summary       TEXT,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_heartbeat_at    TIMESTAMP,
    completion_delivered BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_async_deleg_state
    ON t_async_delegation(state, updated_at);
CREATE INDEX IF NOT EXISTS idx_async_deleg_session
    ON t_async_delegation(parent_session_id);

-- ============================================================
-- P0-3: 会话持久化表（aether_session）— 对齐 docs/postgresql_schema.sql
-- 幂等：重复执行不报错；配合 spring.sql.init.mode=always 每次启动执行
-- ============================================================
CREATE TABLE IF NOT EXISTS aether_session (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id  VARCHAR(128) NOT NULL,
    user_id     VARCHAR(128) NOT NULL,
    agent_id    VARCHAR(128) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    state_json  TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_session_id UNIQUE (session_id)
);

CREATE INDEX IF NOT EXISTS idx_session_user_id    ON aether_session (user_id);
CREATE INDEX IF NOT EXISTS idx_session_agent_id   ON aether_session (agent_id);
CREATE INDEX IF NOT EXISTS idx_session_status     ON aether_session (status);
CREATE INDEX IF NOT EXISTS idx_session_updated_at ON aether_session (updated_at);
