CREATE TABLE IF NOT EXISTS aether_session (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id  VARCHAR(128) NOT NULL,
    user_id     VARCHAR(128) NOT NULL,
    agent_id    VARCHAR(128) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    state_json  TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_session_id UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS aether_memories (
    id               VARCHAR(64)  NOT NULL,
    content          TEXT         NOT NULL,
    embedding        TEXT,
    scope_path       VARCHAR(512),
    scope_private    BOOLEAN      NOT NULL DEFAULT false,
    categories       JSONB        NOT NULL DEFAULT '[]'::jsonb,
    importance       REAL         NOT NULL DEFAULT 0.5,
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    source           VARCHAR(64)  NOT NULL DEFAULT 'agent_extracted',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    access_count     INTEGER      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
