-- ============================================================================
-- Aether Agent — PostgreSQL 数据库建表脚本（单一数据库 aether）
-- ============================================================================
-- 生成依据：
--   PgSessionRepository.java   — aether_session 表（会话持久化）
--   PgvectorVectorStore.java   — aether_memories 表（向量记忆存储）
--   SessionEntity.java         — 会话实体字段定义
--   MemoryRecord.java          — 记忆实体字段定义
-- ============================================================================
-- 前置要求:
--   1. PostgreSQL 16+ (已验证 18.1)
--   2. 数据库: CREATE DATABASE aether;
--   3. pgvector 扩展（可选，用于 aether_memories 向量索引；未安装时 embedding 降级为 TEXT）
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 表: aether_session — Agent 会话持久化表
-- 对应: PgSessionRepository (INSERT ... ON CONFLICT (session_id) DO UPDATE)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aether_session (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id  VARCHAR(128) NOT NULL,
    user_id     VARCHAR(128) NOT NULL,
    agent_id    VARCHAR(128) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    state_json  TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_session_id UNIQUE (session_id)
);

CREATE INDEX IF NOT EXISTS idx_session_user_id    ON aether_session (user_id);
CREATE INDEX IF NOT EXISTS idx_session_agent_id   ON aether_session (agent_id);
CREATE INDEX IF NOT EXISTS idx_session_status     ON aether_session (status);
CREATE INDEX IF NOT EXISTS idx_session_updated_at ON aether_session (updated_at);

COMMENT ON TABLE  aether_session            IS 'Agent 会话持久化表';
COMMENT ON COLUMN aether_session.id         IS '自增主键';
COMMENT ON COLUMN aether_session.session_id IS '会话唯一标识（业务主键）';
COMMENT ON COLUMN aether_session.user_id    IS '用户 ID';
COMMENT ON COLUMN aether_session.agent_id   IS 'Agent ID';
COMMENT ON COLUMN aether_session.status     IS '会话状态: ACTIVE / ARCHIVED / ERROR';
COMMENT ON COLUMN aether_session.state_json IS 'AgentState JSON 序列化数据';
COMMENT ON COLUMN aether_session.created_at IS '创建时间';
COMMENT ON COLUMN aether_session.updated_at IS '更新时间';

-- ----------------------------------------------------------------------------
-- 表: aether_memories — Agent 记忆向量存储表
-- 对应: PgvectorVectorStore (INSERT ... ON CONFLICT (id) DO UPDATE)
-- 说明: embedding 列使用 TEXT 类型存储 '[x1,x2,...,x1024]' 格式向量，兼容未安装
--       pgvector 的 PostgreSQL 实例。安装 pgvector 后执行:
--         ALTER TABLE aether_memories ALTER COLUMN embedding TYPE vector(1024)
--           USING embedding::vector;
--       然后取消下方 HNSW 索引注释并执行。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aether_memories (
    id               VARCHAR(64)  NOT NULL,
    content          TEXT         NOT NULL,
    embedding        TEXT,
    scope_path       VARCHAR(512),
    scope_private    BOOLEAN      NOT NULL DEFAULT false,
    categories       JSONB        NOT NULL DEFAULT '[]'::jsonb,
    importance       REAL         NOT NULL DEFAULT 0.5,
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    source           VARCHAR(64)  NOT NULL DEFAULT 'agent_extracted',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    access_count     INTEGER      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_memories_scope_path    ON aether_memories (scope_path);
CREATE INDEX IF NOT EXISTS idx_memories_created_at    ON aether_memories (created_at);
CREATE INDEX IF NOT EXISTS idx_memories_source        ON aether_memories (source);
CREATE INDEX IF NOT EXISTS idx_memories_importance    ON aether_memories (importance);
CREATE INDEX IF NOT EXISTS idx_memories_last_accessed ON aether_memories (last_accessed_at);

-- [需 pgvector] HNSW 向量索引 — 安装 pgvector 且 embedding 列已 ALTER 为 vector(1024) 后取消注释:
-- CREATE INDEX IF NOT EXISTS idx_memories_embedding_hnsw ON aether_memories
--     USING hnsw (embedding vector_cosine_ops);
-- 应用启动时也会幂等尝试创建该索引（失败仅告警）。

COMMENT ON TABLE  aether_memories                  IS 'Agent 记忆向量存储表';
COMMENT ON COLUMN aether_memories.id               IS '记忆唯一标识';
COMMENT ON COLUMN aether_memories.content          IS '记忆文本内容';
COMMENT ON COLUMN aether_memories.embedding        IS 'Embedding 向量（TEXT 格式，安装 pgvector 后可 ALTER 为 vector(1024)）';
COMMENT ON COLUMN aether_memories.scope_path       IS '作用域路径（层级命名空间）';
COMMENT ON COLUMN aether_memories.scope_private    IS '是否私密记忆';
COMMENT ON COLUMN aether_memories.categories       IS '分类标签（JSONB 数组）';
COMMENT ON COLUMN aether_memories.importance       IS '重要性评分（0.0 ~ 1.0）';
COMMENT ON COLUMN aether_memories.metadata         IS '扩展元数据（JSONB 对象）';
COMMENT ON COLUMN aether_memories.source           IS '来源: user_manual / agent_extracted / system';
COMMENT ON COLUMN aether_memories.created_at       IS '创建时间';
COMMENT ON COLUMN aether_memories.last_accessed_at IS '最后访问时间';
COMMENT ON COLUMN aether_memories.access_count     IS '访问次数';
